#!/usr/bin/env python3

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap
import os
import sys


yaml = YAML()

yaml.dump(CommentedMap(sorted(list(os.environ.items()))),
          sys.stdout)
