#!/usr/bin/env python3

import os
import hashlib

MAX_FILE_SIZE_HASH = 1024*1024 # 1 MB

def md5(fname):
  """  Get md5 hash of file. See: https://stackoverflow.com/a/3431838 """
  hash_md5 = hashlib.md5()
  with open(fname, "rb") as f:
    for chunk in iter(lambda: f.read(4096), b""):
      hash_md5.update(chunk)
  return hash_md5.hexdigest()

for root, dirs, files in os.walk("."):
    for file in files:
        filepath = os.path.join(root, file)
        # Get stats on this file
        file_size_bytes = os.path.getsize(filepath)
        file_mod_time = os.path.getmtime(filepath)
        file_hash = ("-"*32) if (file_size_bytes > MAX_FILE_SIZE_HASH) else md5(filepath)
        # Print the stats
        print (file_size_bytes, str(file_mod_time)[:16], file_hash, filepath, sep='\t')
