#!/usr/bin/env python3

import os
import hashlib

MAX_FILE_SIZE_HASH = 1024*1024 # 1 MB

def md5(fname):
  """  Get md5 hash of file. See: https://stackoverflow.com/a/3431838 """
  hash_md5 = hashlib.md5()
  with open(fname, "rb") as f:
    for chunk in iter(lambda: f.read(4096), b""):
      hash_md5.update(chunk)
  return hash_md5.hexdigest()

for root, dirs, files in os.walk("."):
    # print((len(path) - 1) * '---', os.path.basename(root))
    for file in files:
        filepath = os.path.join(root, file)
        # Generate stats on this file
        file_size_bytes = os.path.getsize(filepath)
        file_mod_time = os.path.getmtime(filepath)
        file_hash = "" if (file_size_bytes > MAX_FILE_SIZE_HASH) else md5(filepath)
        print (file_size_bytes, file_mod_time, file_hash, filepath, sep='\t')
